[package]
name = "rustboy"
version = "0.1.0"
edition = "2021"
build = "./src/build.rs"

[dependencies]
sdl2 = "*"
miniquad = "0.4.5"
byteorder = "1.4"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
fps_counter = "3.0.0"


