[package]
name = "rustboy"
version = "0.1.0"
edition = "2021"
build = "./src/build.rs"

[dependencies]
sdl2 = "*"
fps_counter = "3.0.0"
crossbeam-channel = "0.5.13"
GBcore = { path = "./cores/GBcore" }


